Try caching Google Cloud SDK

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -750,7 +750,6 @@ workflows:
     - activate-ssh-key@4:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@6.2: {}
-    - cache-pull@2.1: {}
     - certificate-and-profile-installer@1.10: {}
     - script@1:
         inputs:
@@ -779,20 +778,43 @@ workflows:
         - configuration: FocusDebug
         - project_path: "$BITRISE_PROJECT_PATH"
     - deploy-to-bitrise-io@2.0: {}
+    - cache-pull@2.7.2: 
+        inputs:
+        - cache_paths: "$HOME/google-cloud-sdk"
     - script@1:
-        title: Firebase Test Lab Setup & Execution
+        title: Install Google Cloud SDK
         inputs:
         - content: |-
             #!/usr/bin/env bash
             set -e
-            curl https://sdk.cloud.google.com > install.sh
-            bash install.sh --disable-prompts
-            source $HOME/google-cloud-sdk/path.bash.inc
-            gcloud components install beta
+            
+            if [ -e $HOME/google-cloud-sdk ]; then
+              echo "Google Cloud SDK found, skipping installation..."
+            else
+              echo "Google Cloud SDK not found, installing..."
+              curl https://sdk.cloud.google.com > install.sh
+              bash install.sh --disable-prompts
+              source $HOME/google-cloud-sdk/path.bash.inc
+              gcloud components install beta
+            fi
+    - cache-push@2.7.1:
+        run_if: .IsPR
+        inputs:
+        - cache_paths: "$HOME/google-cloud-sdk"
+        - ignore_check_on_paths: "!/Users/vagrant/Library/Developer/Xcode/DerivedData/**"
+        - compress_archive: "true"
+    - script@1:
+        title: Firebase Test Lab Execution
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -e 
+
             curl -o /tmp/key-file.json $BITRISEIO_GOOGLE_APPLICATION_CREDENTIALS_URL 
-            gcloud auth activate-service-account -q --key-file /tmp/key-file.json
-            gcloud config set project moz-firefox-ios-230118
-            gcloud beta firebase test ios run \
+            $HOME/google-cloud-sdk/bin/gcloud version
+            $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account -q --key-file /tmp/key-file.json
+            $HOME/google-cloud-sdk/bin/gcloud config set project moz-firefox-ios-230118
+            $HOME/google-cloud-sdk/bin/gcloud beta firebase test ios run \
             --type robo \
             --app "$BITRISE_IPA_PATH" \
             --device=model=iphone13pro,version=15.7 \
