script in both

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -297,26 +297,6 @@ workflows:
     - cache-push@2:
         inputs:
         - cache_paths: "/Users/vagrant/git"
-    - script@1:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            set -x
-
-            # Check if the build is a scheduled build
-
-            if [[ $BITRISE_GIT_MESSAGE == Schedule* ]]
-            then
-                echo "Scheduled build, running Full Functional Tests"
-                envman add --key TEST_PLAN_NAME --value FullFunctionalTests
-            else
-                echo "Regular build, running Smoke Test"
-                envman add --key TEST_PLAN_NAME --value SmokeTest
-            fi
-        - title: Check if build is scheduled or regular to set the test plan
     - build-router-start@0:
         inputs:
         - wait_for_builds: 'true'
@@ -348,6 +328,26 @@ workflows:
     - git-clone@4: {}
     - cache-pull@2: {}
     - certificate-and-profile-installer@1: {}
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Check if the build is a scheduled build
+
+            if [[ $BITRISE_GIT_MESSAGE == Schedule* ]]
+            then
+                echo "Scheduled build, running Full Functional Tests"
+                envman add --key TEST_PLAN_NAME --value FullFunctionalTests
+            else
+                echo "Regular build, running Smoke Test"
+                envman add --key TEST_PLAN_NAME --value SmokeTest
+            fi
+        - title: Check if build is scheduled or regular to set the test plan
     - script@1:
         inputs:
         - content: |-
@@ -391,6 +391,26 @@ workflows:
         inputs:
         - content: |-
             #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Check if the build is a scheduled build
+
+            if [[ $BITRISE_GIT_MESSAGE == Schedule* ]]
+            then
+                echo "Scheduled build, running Full Functional Tests"
+                envman add --key TEST_PLAN_NAME --value FullFunctionalTests
+            else
+                echo "Regular build, running Smoke Test"
+                envman add --key TEST_PLAN_NAME --value SmokeTest
+            fi
+        - title: Check if build is scheduled or regular to set the test plan
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
             ./checkout.sh
         title: ContentBlockerGen
     - script@1:
@@ -409,7 +429,7 @@ workflows:
     - xcode-test@2:
         inputs:
         - xcodebuild_test_options: CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
-            CODE_SIGNING_ALLOWED=NO -maximum-parallel-testing-workers 2 -testPlan $TEST_PLAN_NAME
+            CODE_SIGNING_ALLOWED=NO -maximum-parallel-testing-workers 2 -testPlan "$TEST_PLAN_NAME"
         - scheme: Klar
     - cache-push@2:
         inputs:
